[module.hugoVersion]
min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.content_panel]
bottom = '20px'
comments = true

# [params.hb.content_panel.repo]
# service = "github"
# repo = "user/name"
# branch = "main"
# subpath = "exampleSite"
